aliases:
    - &configure
        - run:
            name: Fetching submodules
            command: 'bash configure.sh'
    - &building
        - run:
            name: Building
            command: 'cmake --build build -j2'
    - &testing
        - run:
            name: Unit Testing
            command: 'pushd build && ctest --output-on-failure -j2'

version: 2
jobs:
  build-clang-release:
    docker:
      - image: evillhood/arch-builder:latest
    steps:
      - checkout
      - *configure
      - run:
          name: Generating build files
          command: 'cmake -Bbuild -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_STANDARD=14 -DCMAKE_BUILD_TYPE=Release'
      - *building
      - *testing
  build-gcc-release:
    docker:
      - image: evillhood/arch-builder:latest
    steps:
      - checkout
      - *configure
      - run:
          name: Generating build files
          command: 'cmake -Bbuild -DCMAKE_CXX_COMPILER=g++ -DCMAKE_C_COMPILER=gcc -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Release'
      - *building
      - *testing
  build-clang-debug:
    docker:
      - image: evillhood/arch-builder:latest
    steps:
      - checkout
      - *configure
      - run:
          name: Generating build files
          command: 'cmake -Bbuild -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_STANDARD=17 -DCMAKE_BUILD_TYPE=Debug -DSANITIZE=ON'
      - *building
      - *testing
workflows:
  version: 2
  build:
    jobs:
      - build-clang-debug
      - build-clang-release
      - build-gcc-release
