version: 2
jobs:
  build-gcc-default:
    docker:
      - image: evillhood/arch-builder:latest
    steps:
      - checkout
      - run:
          name: Fetching submodules
          command: 'bash configure.sh'
      - run:
          name: Generating build files
          command: 'cmake -Bbuild'
      - run:
          name: Building
          command: 'cmake --build build -j2'
      - run:
          name: Unit Testing
          command: 'pushd build && ctest -j2'
workflows:
  version: 2
  build:
    jobs:
      - build-gcc-default
